Traceback (most recent call last):
  File "/Users/coni/.local/share/virtualenvs/Jupyter-Book-AWX1Chim/lib/python3.6/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/coni/.local/share/virtualenvs/Jupyter-Book-AWX1Chim/lib/python3.6/site-packages/nbclient/client.py", line 1117, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/coni/.local/share/virtualenvs/Jupyter-Book-AWX1Chim/lib/python3.6/site-packages/nbclient/util.py", line 78, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/coni/.local/share/virtualenvs/Jupyter-Book-AWX1Chim/lib/python3.6/site-packages/nbclient/util.py", line 57, in just_run
    return loop.run_until_complete(coro)
  File "/Users/coni/anaconda/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/Users/coni/.local/share/virtualenvs/Jupyter-Book-AWX1Chim/lib/python3.6/site-packages/nbclient/client.py", line 559, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/coni/.local/share/virtualenvs/Jupyter-Book-AWX1Chim/lib/python3.6/site-packages/nbclient/client.py", line 862, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/coni/.local/share/virtualenvs/Jupyter-Book-AWX1Chim/lib/python3.6/site-packages/nbclient/client.py", line 765, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# Und jetzt: Plotly! 
import plotly.express as px

# Plotly Express bringt selbst schon einige Datens√§tze mit: 
df = px.data.gapminder()

df.head()
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m<ipython-input-1-b5c2fca68f18>[0m in [0;36m<module>[0;34m[0m
[1;32m      1[0m [0;31m# Und jetzt: Plotly![0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 2[0;31m [0;32mimport[0m [0mplotly[0m[0;34m.[0m[0mexpress[0m [0;32mas[0m [0mpx[0m[0;34m[0m[0m
[0m[1;32m      3[0m [0;34m[0m[0m
[1;32m      4[0m [0;31m# Plotly Express bringt selbst schon einige Datens√§tze mit:[0m[0;34m[0m[0;34m[0m[0m
[1;32m      5[0m [0mdf[0m [0;34m=[0m [0mpx[0m[0;34m.[0m[0mdata[0m[0;34m.[0m[0mgapminder[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'plotly'
ModuleNotFoundError: No module named 'plotly'

